on:
  push:
    tags:
      - 'v*'

name: GitHub Release

jobs:
  github-release:
    name: gh-release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: gh-release
        id: gh_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            See [CHANGELOG.md](./CHANGELOG.md) for changes.
          draft: false
          prerelease: false
